FROM fusuf/whatsasena:latest

RUN git clone https://github.com/Tdg234/Amalser_v2 /root/WhatsAsenaDuplicated
WORKDIR /root/WhatsAsenaDuplicated/
ENV TZ=Europe/Istanbul
RUN npm install supervisor -g
RUN yarn install --no-audit
RUN git clone https://github.com/Tdg234/Amalser_v2 /media 

CMD ["node", "bot.js"]
